version: "3.9"

services:
  # Servicio de base de datos PostgreSQL
  liter-postgre:
    image: postgres:16-alpine
    container_name: liter-postgre
    environment:
      POSTGRES_DB: liter
      POSTGRES_USER: bibliotecario
      POSTGRES_PASSWORD: liter41ur4
    ports:
      - "5432:5432"

  # Servicio de tu aplicación Java
  liter-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: liter-app
    depends_on:
      - liter-postgre
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://liter-postgre:5432/liter
      SPRING_DATASOURCE_USERNAME: bibliotecario
      SPRING_DATASOURCE_PASSWORD: liter41ur4
    stdin_open: true     # Para que acepte entrada interactiva (Scanner)
    tty: true            # Asigna terminal

volumes:
  pgdata: